// Code generated by fastssz. DO NOT EDIT.
// Hash: b8acffe45d77830168eada3d7d7451ca6246597a7d21f28f298333d0eb42399a
// Version: 0.1.3
package ethmsg

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the ColumnBlockHeader object
func (c *ColumnBlockHeader) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(c)
}

// MarshalSSZTo ssz marshals the ColumnBlockHeader object to a target array
func (c *ColumnBlockHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, c.Slot)

	// Field (1) 'ProposerIndex'
	dst = ssz.MarshalUint64(dst, c.ProposerIndex)

	// Field (2) 'ParentRoot'
	dst = append(dst, c.ParentRoot[:]...)

	// Field (3) 'StateRoot'
	dst = append(dst, c.StateRoot[:]...)

	// Field (4) 'BodyRoot'
	dst = append(dst, c.BodyRoot[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the ColumnBlockHeader object
func (c *ColumnBlockHeader) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 112 {
		return ssz.ErrSize
	}

	// Field (0) 'Slot'
	c.Slot = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'ProposerIndex'
	c.ProposerIndex = ssz.UnmarshallUint64(buf[8:16])

	// Field (2) 'ParentRoot'
	copy(c.ParentRoot[:], buf[16:48])

	// Field (3) 'StateRoot'
	copy(c.StateRoot[:], buf[48:80])

	// Field (4) 'BodyRoot'
	copy(c.BodyRoot[:], buf[80:112])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ColumnBlockHeader object
func (c *ColumnBlockHeader) SizeSSZ() (size int) {
	size = 112
	return
}

// HashTreeRoot ssz hashes the ColumnBlockHeader object
func (c *ColumnBlockHeader) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(c)
}

// HashTreeRootWith ssz hashes the ColumnBlockHeader object with a hasher
func (c *ColumnBlockHeader) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	hh.PutUint64(c.Slot)

	// Field (1) 'ProposerIndex'
	hh.PutUint64(c.ProposerIndex)

	// Field (2) 'ParentRoot'
	hh.PutBytes(c.ParentRoot[:])

	// Field (3) 'StateRoot'
	hh.PutBytes(c.StateRoot[:])

	// Field (4) 'BodyRoot'
	hh.PutBytes(c.BodyRoot[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the ColumnBlockHeader object
func (c *ColumnBlockHeader) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(c)
}

// MarshalSSZ ssz marshals the ColumnSignedBlockHeader object
func (c *ColumnSignedBlockHeader) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(c)
}

// MarshalSSZTo ssz marshals the ColumnSignedBlockHeader object to a target array
func (c *ColumnSignedBlockHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Message'
	if c.Message == nil {
		c.Message = new(ColumnBlockHeader)
	}
	if dst, err = c.Message.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (1) 'Signature'
	dst = append(dst, c.Signature[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the ColumnSignedBlockHeader object
func (c *ColumnSignedBlockHeader) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 208 {
		return ssz.ErrSize
	}

	// Field (0) 'Message'
	if c.Message == nil {
		c.Message = new(ColumnBlockHeader)
	}
	if err = c.Message.UnmarshalSSZ(buf[0:112]); err != nil {
		return err
	}

	// Field (1) 'Signature'
	copy(c.Signature[:], buf[112:208])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the ColumnSignedBlockHeader object
func (c *ColumnSignedBlockHeader) SizeSSZ() (size int) {
	size = 208
	return
}

// HashTreeRoot ssz hashes the ColumnSignedBlockHeader object
func (c *ColumnSignedBlockHeader) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(c)
}

// HashTreeRootWith ssz hashes the ColumnSignedBlockHeader object with a hasher
func (c *ColumnSignedBlockHeader) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Message'
	if c.Message == nil {
		c.Message = new(ColumnBlockHeader)
	}
	if err = c.Message.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (1) 'Signature'
	hh.PutBytes(c.Signature[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the ColumnSignedBlockHeader object
func (c *ColumnSignedBlockHeader) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(c)
}

// MarshalSSZ ssz marshals the DataColumnSidecar object
func (d *DataColumnSidecar) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(d)
}

// MarshalSSZTo ssz marshals the DataColumnSidecar object to a target array
func (d *DataColumnSidecar) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(356)

	// Field (0) 'Index'
	dst = ssz.MarshalUint64(dst, d.Index)

	// Offset (1) 'Column'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(d.Column) * 2048

	// Offset (2) 'KZGCommitments'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(d.KZGCommitments) * 48

	// Offset (3) 'KZGProofs'
	dst = ssz.WriteOffset(dst, offset)

	// Field (4) 'SignedBlockHeader'
	if d.SignedBlockHeader == nil {
		d.SignedBlockHeader = new(ColumnSignedBlockHeader)
	}
	if dst, err = d.SignedBlockHeader.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (5) 'KZGCommitmentsInclusionProof'
	if size := len(d.KZGCommitmentsInclusionProof); size != 4 {
		err = ssz.ErrVectorLengthFn("DataColumnSidecar.KZGCommitmentsInclusionProof", size, 4)
		return
	}
	for ii := 0; ii < 4; ii++ {
		dst = append(dst, d.KZGCommitmentsInclusionProof[ii][:]...)
	}

	// Field (1) 'Column'
	if size := len(d.Column); size > 4096 {
		err = ssz.ErrListTooBigFn("DataColumnSidecar.Column", size, 4096)
		return
	}
	for ii := 0; ii < len(d.Column); ii++ {
		dst = append(dst, d.Column[ii][:]...)
	}

	// Field (2) 'KZGCommitments'
	if size := len(d.KZGCommitments); size > 4096 {
		err = ssz.ErrListTooBigFn("DataColumnSidecar.KZGCommitments", size, 4096)
		return
	}
	for ii := 0; ii < len(d.KZGCommitments); ii++ {
		dst = append(dst, d.KZGCommitments[ii][:]...)
	}

	// Field (3) 'KZGProofs'
	if size := len(d.KZGProofs); size > 4096 {
		err = ssz.ErrListTooBigFn("DataColumnSidecar.KZGProofs", size, 4096)
		return
	}
	for ii := 0; ii < len(d.KZGProofs); ii++ {
		dst = append(dst, d.KZGProofs[ii][:]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the DataColumnSidecar object
func (d *DataColumnSidecar) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 356 {
		return ssz.ErrSize
	}

	tail := buf
	var o1, o2, o3 uint64

	// Field (0) 'Index'
	d.Index = ssz.UnmarshallUint64(buf[0:8])

	// Offset (1) 'Column'
	if o1 = ssz.ReadOffset(buf[8:12]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 356 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (2) 'KZGCommitments'
	if o2 = ssz.ReadOffset(buf[12:16]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Offset (3) 'KZGProofs'
	if o3 = ssz.ReadOffset(buf[16:20]); o3 > size || o2 > o3 {
		return ssz.ErrOffset
	}

	// Field (4) 'SignedBlockHeader'
	if d.SignedBlockHeader == nil {
		d.SignedBlockHeader = new(ColumnSignedBlockHeader)
	}
	if err = d.SignedBlockHeader.UnmarshalSSZ(buf[20:228]); err != nil {
		return err
	}

	// Field (5) 'KZGCommitmentsInclusionProof'
	d.KZGCommitmentsInclusionProof = make([][32]byte, 4)
	for ii := 0; ii < 4; ii++ {
		copy(d.KZGCommitmentsInclusionProof[ii][:], buf[228:356][ii*32:(ii+1)*32])
	}

	// Field (1) 'Column'
	{
		buf = tail[o1:o2]
		num, err := ssz.DivideInt2(len(buf), 2048, 4096)
		if err != nil {
			return err
		}
		d.Column = make([][2048]byte, num)
		for ii := 0; ii < num; ii++ {
			copy(d.Column[ii][:], buf[ii*2048:(ii+1)*2048])
		}
	}

	// Field (2) 'KZGCommitments'
	{
		buf = tail[o2:o3]
		num, err := ssz.DivideInt2(len(buf), 48, 4096)
		if err != nil {
			return err
		}
		d.KZGCommitments = make([][48]byte, num)
		for ii := 0; ii < num; ii++ {
			copy(d.KZGCommitments[ii][:], buf[ii*48:(ii+1)*48])
		}
	}

	// Field (3) 'KZGProofs'
	{
		buf = tail[o3:]
		num, err := ssz.DivideInt2(len(buf), 48, 4096)
		if err != nil {
			return err
		}
		d.KZGProofs = make([][48]byte, num)
		for ii := 0; ii < num; ii++ {
			copy(d.KZGProofs[ii][:], buf[ii*48:(ii+1)*48])
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the DataColumnSidecar object
func (d *DataColumnSidecar) SizeSSZ() (size int) {
	size = 356

	// Field (1) 'Column'
	size += len(d.Column) * 2048

	// Field (2) 'KZGCommitments'
	size += len(d.KZGCommitments) * 48

	// Field (3) 'KZGProofs'
	size += len(d.KZGProofs) * 48

	return
}

// HashTreeRoot ssz hashes the DataColumnSidecar object
func (d *DataColumnSidecar) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(d)
}

// HashTreeRootWith ssz hashes the DataColumnSidecar object with a hasher
func (d *DataColumnSidecar) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Index'
	hh.PutUint64(d.Index)

	// Field (1) 'Column'
	{
		if size := len(d.Column); size > 4096 {
			err = ssz.ErrListTooBigFn("DataColumnSidecar.Column", size, 4096)
			return
		}
		subIndx := hh.Index()
		for _, i := range d.Column {
			hh.PutBytes(i[:])
		}
		numItems := uint64(len(d.Column))
		hh.MerkleizeWithMixin(subIndx, numItems, 4096)
	}

	// Field (2) 'KZGCommitments'
	{
		if size := len(d.KZGCommitments); size > 4096 {
			err = ssz.ErrListTooBigFn("DataColumnSidecar.KZGCommitments", size, 4096)
			return
		}
		subIndx := hh.Index()
		for _, i := range d.KZGCommitments {
			hh.PutBytes(i[:])
		}
		numItems := uint64(len(d.KZGCommitments))
		hh.MerkleizeWithMixin(subIndx, numItems, 4096)
	}

	// Field (3) 'KZGProofs'
	{
		if size := len(d.KZGProofs); size > 4096 {
			err = ssz.ErrListTooBigFn("DataColumnSidecar.KZGProofs", size, 4096)
			return
		}
		subIndx := hh.Index()
		for _, i := range d.KZGProofs {
			hh.PutBytes(i[:])
		}
		numItems := uint64(len(d.KZGProofs))
		hh.MerkleizeWithMixin(subIndx, numItems, 4096)
	}

	// Field (4) 'SignedBlockHeader'
	if d.SignedBlockHeader == nil {
		d.SignedBlockHeader = new(ColumnSignedBlockHeader)
	}
	if err = d.SignedBlockHeader.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (5) 'KZGCommitmentsInclusionProof'
	{
		if size := len(d.KZGCommitmentsInclusionProof); size != 4 {
			err = ssz.ErrVectorLengthFn("DataColumnSidecar.KZGCommitmentsInclusionProof", size, 4)
			return
		}
		subIndx := hh.Index()
		for _, i := range d.KZGCommitmentsInclusionProof {
			hh.Append(i[:])
		}
		hh.Merkleize(subIndx)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the DataColumnSidecar object
func (d *DataColumnSidecar) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(d)
}
