package main

import (
	"fmt"
	"strings"
)

// render_machines.go — emits the machine definitions consumed by the walker
// in cases/irwalker.go: func irMachineDefs() []*irMachine. Guards compile to
// Go closures over *irContext with fork atoms separated into ForkGte/ForkIn;
// generating_mode compiles to false (we are executing, not generating).

// renderMachineDefsFile renders every machine into one Go source file.
func renderMachineDefsFile(machines []*Machine, pkg, source string, pm *ProtocolModel) (string, error) {
	var file strings.Builder
	file.WriteString("// Code generated by smgen; DO NOT EDIT.\n")
	fmt.Fprintf(&file, "// Source: %s.\n\n", source)
	fmt.Fprintf(&file, "package %s\n\n", pkg)
	needBinary := strings.Contains(file.String(), "") // set below after bodies
	var bodies strings.Builder
	for _, m := range machines {
		var b strings.Builder
		if err := renderMachineDef(&b, m, pm); err != nil {
			return "", fmt.Errorf("machine %q: %w", m.Name, err)
		}
		bodies.WriteString(b.String())
	}
	needBinary = strings.Contains(bodies.String(), "binary.")
	file.WriteString("import (\n")
	if needBinary {
		file.WriteString("\t\"encoding/binary\"\n")
	}
	file.WriteString("\t\"parallax/wire\"\n)\n\n")
	file.WriteString("// irMachineDefs returns the SM-IR machine definitions for the walker.\n")
	file.WriteString("func irMachineDefs() []*irMachine {\n")
	file.WriteString("\treturn []*irMachine{\n")
	file.WriteString(bodies.String())
	file.WriteString("\t}\n}\n")
	return formatCaseSource(&file)
}

func renderMachineDef(b *strings.Builder, m *Machine, pm *ProtocolModel) error {
	fmt.Fprintf(b, "\t\t{\n")
	fmt.Fprintf(b, "\t\t\tName: %q,\n\t\t\tInitState: %q,\n", m.Name, m.InitState)
	fmt.Fprintf(b, "\t\t\tTransitions: []irTransition{\n")
	for i := range m.Transitions {
		if err := renderTransitionDef(b, &m.Transitions[i], pm); err != nil {
			return fmt.Errorf("transition %q: %w", m.Transitions[i].Label, err)
		}
	}
	fmt.Fprintf(b, "\t\t\t},\n")
	fmt.Fprintf(b, "\t\t},\n")
	return nil
}

func renderTransitionDef(b *strings.Builder, t *Transition, pm *ProtocolModel) error {
	fmt.Fprintf(b, "\t\t\t{\n")
	fmt.Fprintf(b, "\t\t\t\tFrom: %q, To: %q, Label: %q, Weight: %d,\n", t.From, t.To, t.Label, t.Weight)
	if len(t.SpecRefs) > 0 {
		fmt.Fprintf(b, "\t\t\t\tSpecRefs: %s,\n", goStringSlice(t.SpecRefs))
	}
	if t.Guard != nil {
		gte, in, residual, err := splitForkGuard(t.Guard)
		if err != nil {
			return err
		}
		if gte != "" {
			fmt.Fprintf(b, "\t\t\t\tForkGte: %q,\n", gte)
		}
		if len(in) > 0 {
			fmt.Fprintf(b, "\t\t\t\tForkIn: %s,\n", goStringSlice(in))
		}
		if residual != nil {
			expr, err := compileGuardExpr(residual)
			if err != nil {
				return err
			}
			fmt.Fprintf(b, "\t\t\t\tGuard: func(g *irContext) bool { return %s },\n", expr)
		}
	}
	fmt.Fprintf(b, "\t\t\t\tActionType: %q,\n", t.Action.Type)
	if t.Action.Protocol != "" {
		fmt.Fprintf(b, "\t\t\t\tProtocol: %q,\n", t.Action.Protocol)
	}
	if t.Action.TimeoutMs > 0 {
		fmt.Fprintf(b, "\t\t\t\tTimeoutMs: %d,\n", t.Action.TimeoutMs)
	}
	if t.Action.Mutator != "" {
		fmt.Fprintf(b, "\t\t\t\tMutator: %q,\n", t.Action.Mutator)
	}
	if t.Action.RepeatCount > 0 {
		fmt.Fprintf(b, "\t\t\t\tRepeatCount: %d,\n", t.Action.RepeatCount)
	}
	if t.Action.KeepWriteOpen {
		fmt.Fprintf(b, "\t\t\t\tKeepWriteOpen: true,\n")
	}
	if p := t.Action.Payload; p != nil && caseSkip(t) == "" {
		body, err := compilePayloadClosure(p, t.Action.Protocol, pm)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "\t\t\t\tPayload: %s,\n", body)
	}
	fmt.Fprintf(b, "\t\t\t},\n")
	return nil
}

// compilePayloadClosure renders a func(g *irContext) []byte literal for the
// payload, using only builders available in the cases package.
func compilePayloadClosure(p *Payload, protocol string, pm *ProtocolModel) (string, error) {
	switch p.Kind {
	case "builder":
		return fmt.Sprintf("func(g *irContext) []byte { return %s(g) }", p.Name), nil
	case "literal":
		var inner string
		switch {
		case p.Null:
			inner = "nil"
		case p.Size != nil:
			inner = fmt.Sprintf("make([]byte, %d)", *p.Size)
		case p.Bytes != "":
			lit, err := hexToGoBytes(p.Bytes)
			if err != nil {
				return "", err
			}
			inner = lit
		default:
			return "", fmt.Errorf("literal payload has no bytes/size/null")
		}
		return fmt.Sprintf("func(g *irContext) []byte { return %s }", wrapExprCases(p.Wrap, inner)), nil
	case "fields":
		return compileFieldsClosure(p, protocol, pm)
	default:
		return "", fmt.Errorf("unknown payload kind %q", p.Kind)
	}
}

// compileFieldsClosure renders a fixed-container SSZ encoder closure over the
// protocol model's field layout.
func compileFieldsClosure(p *Payload, protocol string, pm *ProtocolModel) (string, error) {
	if pm == nil {
		return "", fmt.Errorf("fields payload requires a protocol model")
	}
	method, ok := pm.method(protocol)
	if !ok {
		return "", fmt.Errorf("no protocol model entry for %q", protocol)
	}
	if method.Request.Container != "fixed" {
		return "", fmt.Errorf("fields codegen requires a fixed container; method %s is %q", method.Name, method.Request.Container)
	}
	total := 0
	for _, f := range method.Request.Fields {
		total += f.Size
	}
	var b strings.Builder
	b.WriteString("func(g *irContext) []byte {\n")
	fmt.Fprintf(&b, "\tbuf := make([]byte, %d)\n", total)
	off := 0
	for _, f := range method.Request.Fields {
		fv, present := p.Fields[f.Name]
		if !present {
			return "", fmt.Errorf("missing field %q for method %s", f.Name, method.Name)
		}
		end := off + f.Size
		switch f.Type {
		case "uint64":
			switch {
			case fv.Lit != nil:
				fmt.Fprintf(&b, "\tbinary.LittleEndian.PutUint64(buf[%d:%d], %d)\n", off, end, *fv.Lit)
			case fv.Ctx != "":
				acc, ok := caseCtxUint64[fv.Ctx]
				if !ok {
					return "", fmt.Errorf("unknown ctx uint64 source %q", fv.Ctx)
				}
				acc = strings.ReplaceAll(acc, "ictx.", "g.")
				fmt.Fprintf(&b, "\tbinary.LittleEndian.PutUint64(buf[%d:%d], %s)\n", off, end, acc)
			default:
				return "", fmt.Errorf("field %q (uint64) needs lit or ctx", f.Name)
			}
		case "bytes":
			if fv.Ctx != "" {
				acc, ok := caseCtxBytes[fv.Ctx]
				if !ok {
					return "", fmt.Errorf("unknown ctx bytes source %q", fv.Ctx)
				}
				acc = strings.ReplaceAll(acc, "ictx.", "g.")
				fmt.Fprintf(&b, "\tcopy(buf[%d:%d], %s)\n", off, end, acc)
			} else {
				return "", fmt.Errorf("field %q (bytes) needs a ctx source", f.Name)
			}
		default:
			return "", fmt.Errorf("field %q has unsupported type %q", f.Name, f.Type)
		}
		off = end
	}
	b.WriteString("\treturn wire.BuildSSZSnappy(buf)\n")
	b.WriteString("}")
	return b.String(), nil
}

// compileGuardExpr compiles a non-fork guard into a Go boolean expression over
// the *irContext variable named g.
func compileGuardExpr(grd *Guard) (string, error) {
	switch {
	case grd.And != nil:
		return compileGuardComposite(grd.And, "&&")
	case grd.Or != nil:
		return compileGuardComposite(grd.Or, "||")
	case grd.Not != nil:
		sub, err := compileGuardExpr(grd.Not)
		if err != nil {
			return "", err
		}
		return "!(" + sub + ")", nil
	case grd.GeneratingMode != nil:
		return "false", nil
	case grd.Flag != "":
		field, ok := genFlagField[grd.Flag]
		if !ok {
			return "", fmt.Errorf("unknown guard flag %q", grd.Flag)
		}
		return "g." + field, nil
	case grd.Present != "":
		if grd.Present != "enr_snapshot" {
			return "", fmt.Errorf("unknown guard presence predicate %q", grd.Present)
		}
		return "g.DiscENRSnapshot != nil", nil
	case grd.Count != nil:
		field, ok := genCounterField[grd.Count.Field]
		if !ok {
			return "", fmt.Errorf("unknown guard counter field %q", grd.Count.Field)
		}
		return fmt.Sprintf("g.%s %s %d", field, grd.Count.Op, grd.Count.Value), nil
	case grd.Len != nil:
		field, ok := genLenField[grd.Len.Field]
		if !ok {
			return "", fmt.Errorf("unknown guard length field %q", grd.Len.Field)
		}
		return fmt.Sprintf("len(g.%s) %s %d", field, grd.Len.Op, grd.Len.Value), nil
	case grd.LastResultIn != nil:
		// No real IR machine uses last_result_in; compile conservatively to
		// false so the transition is only taken when nothing else applies.
		return "false", nil
	case grd.HasVisited != "":
		return fmt.Sprintf("g.HasVisitedTransition(%q)", grd.HasVisited), nil
	}
	return "", fmt.Errorf("empty guard")
}

func compileGuardComposite(subs []Guard, op string) (string, error) {
	var terms []string
	for i := range subs {
		s, err := compileGuardExpr(&subs[i])
		if err != nil {
			return "", err
		}
		terms = append(terms, s)
	}
	return "(" + strings.Join(terms, " "+op+" ") + ")", nil
}

// guard field name maps: IR names -> irContext field accessors (subset of
// p2p-testing's vocabulary that real machines use).
var (
	genFlagField = map[string]string{
		"status_done":            "StatusDone",
		"disc_we_in_peer_list":   "DiscWeInPeerList",
		"disc_nfd_mismatch_sent": "DiscNFDMismatchSent",
	}
	genCounterField = map[string]string{
		"messages_sent":               "MessagesSent",
		"rejection_count":             "RejectionCount",
		"connection_count":            "ConnectionCount",
		"gossip_violation_count":      "GossipViolationCount",
		"reqresp_failure_count":       "ReqRespFailureCount",
		"custody_columns_requested":   "CustodyColumnsRequested",
		"custody_columns_failed":      "CustodyColumnsFailed",
		"non_custody_requested":       "NonCustodyRequested",
		"reconnect_attempts":          "ReconnectAttempts",
		"decay_wait_count":            "DecayWaitCount",
		"disc_enr_query_count":        "DiscENRQueryCount",
		"disc_peer_list_count":        "DiscPeerListCount",
		"subnet_custody_injected":     "SubnetCustodyInjected",
		"subnet_non_custody_injected": "SubnetNonCustodyInjected",
		"subnet_boundary_injected":    "SubnetBoundaryInjected",
	}
	genLenField = map[string]string{
		"open_streams":               "OpenStreams",
		"step_results":               "StepResults",
		"subnet_custody_subnets":     "SubnetCustodySubnets",
		"subnet_non_custody_subnets": "SubnetNonCustodySubnets",
		"subnet_subscribed_attn":     "SubnetSubscribedAttn",
		"subnet_unsubscribed_attn":   "SubnetUnsubscribedAttn",
		"subnet_subscribed_sync":     "SubnetSubscribedSync",
		"subnet_unsubscribed_sync":   "SubnetUnsubscribedSync",
	}
)
