// Code generated by smgen; DO NOT EDIT.
// Source: knowledge/ir/sequence_tests_generated.json.

package cases

import (
	"context"
	"strings"

	"parallax/runner"
)

// irSequenceSpecs returns every SM-IR sequence case.
func irSequenceSpecs() []runner.Spec {
	var specs []runner.Spec
	{
		id := "ir_seq.cryptomsg.generated_sequence.beacon_aggregate_and_proof.duplicate_first_seen.18d71276"
		specs = append(specs, runner.Spec{
			ID: id, Category: "cryptomsg",
			What:     "cryptomsg.generated_sequence.beacon_aggregate_and_proof.duplicate_first_seen.18d71276: 2-step sequence (1:cm_sequence_beacon_aggregate_and_proof_duplicate_first_seen_setup_18d71276 -> 2:cm_sequence_beacon_aggregate_and_proof_duplicate_first_seen_probe_18d71276)",
			Metadata: runner.Metadata{SpecRules: []string{"BEACON_AGGREGATE_AND_PROOF-IGNORE-7c1a7594"}, MinClients: 2},
			Run: func(ctx context.Context, te runner.TestEnv) []runner.Divergence {
				ictx := irNewContext(te)
				results := map[string]string{}
				for _, cl := range te.Clients {
					var verdicts []string
					// step 1: cm_sequence_beacon_aggregate_and_proof_duplicate_first_seen_setup_18d71276
					payload1 := buildLiveValidBeaconAggregateAndProof(ictx)
					ictx.StorePayload("seq_beacon_aggregate_and_proof_duplicate_first_seen", payload1)
					gtopic1 := irFullGossipTopic(ictx, "beacon_aggregate_and_proof")
					if ictx.GossipTopicOverride != "" {
						gtopic1 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic1 = ictx.CurrentTopic
					}
					gv1, gerr1 := cl.ObserveGossip(ctx, gtopic1, payload1, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv1, gerr1)))
					// step 2: cm_sequence_beacon_aggregate_and_proof_duplicate_first_seen_probe_18d71276
					payload2, _ := ictx.LoadPayload("seq_beacon_aggregate_and_proof_duplicate_first_seen")
					gtopic2 := irFullGossipTopic(ictx, "beacon_aggregate_and_proof")
					if ictx.GossipTopicOverride != "" {
						gtopic2 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic2 = ictx.CurrentTopic
					}
					gv2, gerr2 := cl.ObserveGossip(ctx, gtopic2, payload2, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv2, gerr2)))
					results[cl.Name()] = strings.Join(verdicts, "/")
				}
				return divergeValues(id, "cryptomsg", te, runner.DivAcceptReject, runner.SeverityHigh, results)
			},
		})
	}
	{
		id := "ir_seq.cryptomsg.generated_sequence.blob_sidecar.duplicate_first_seen.d6ec61bd"
		specs = append(specs, runner.Spec{
			ID: id, Category: "cryptomsg",
			What:     "cryptomsg.generated_sequence.blob_sidecar.duplicate_first_seen.d6ec61bd: 2-step sequence (1:cm_sequence_blob_sidecar_duplicate_first_seen_setup_d6ec61bd -> 2:cm_sequence_blob_sidecar_duplicate_first_seen_probe_d6ec61bd)",
			Metadata: runner.Metadata{SpecRules: []string{"BLOB_SIDECAR-IGNORE-ed3428e1"}, MinClients: 2},
			Run: func(ctx context.Context, te runner.TestEnv) []runner.Divergence {
				ictx := irNewContext(te)
				results := map[string]string{}
				for _, cl := range te.Clients {
					var verdicts []string
					// step 1: cm_sequence_blob_sidecar_duplicate_first_seen_setup_d6ec61bd
					payload1 := buildLiveValidBlobSidecar(ictx)
					ictx.StorePayload("seq_blob_sidecar_duplicate_first_seen", payload1)
					gtopic1 := irFullGossipTopic(ictx, "blob_sidecar_0")
					if ictx.GossipTopicOverride != "" {
						gtopic1 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic1 = ictx.CurrentTopic
					}
					gv1, gerr1 := cl.ObserveGossip(ctx, gtopic1, payload1, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv1, gerr1)))
					// step 2: cm_sequence_blob_sidecar_duplicate_first_seen_probe_d6ec61bd
					payload2, _ := ictx.LoadPayload("seq_blob_sidecar_duplicate_first_seen")
					gtopic2 := irFullGossipTopic(ictx, "blob_sidecar_0")
					if ictx.GossipTopicOverride != "" {
						gtopic2 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic2 = ictx.CurrentTopic
					}
					gv2, gerr2 := cl.ObserveGossip(ctx, gtopic2, payload2, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv2, gerr2)))
					results[cl.Name()] = strings.Join(verdicts, "/")
				}
				return divergeValues(id, "cryptomsg", te, runner.DivAcceptReject, runner.SeverityHigh, results)
			},
		})
	}
	{
		id := "ir_seq.cryptomsg.generated_sequence.bls_to_execution_change.duplicate_first_seen.83850e08"
		specs = append(specs, runner.Spec{
			ID: id, Category: "cryptomsg",
			What:     "cryptomsg.generated_sequence.bls_to_execution_change.duplicate_first_seen.83850e08: 2-step sequence (1:cm_sequence_bls_to_execution_change_duplicate_first_seen_setup_83850e08 -> 2:cm_sequence_bls_to_execution_change_duplicate_first_seen_probe_83850e08)",
			Metadata: runner.Metadata{SpecRules: []string{"BLS_TO_EXECUTION_CHANGE-IGNORE-b226c668"}, MinClients: 2},
			Run: func(ctx context.Context, te runner.TestEnv) []runner.Divergence {
				ictx := irNewContext(te)
				results := map[string]string{}
				for _, cl := range te.Clients {
					var verdicts []string
					// step 1: cm_sequence_bls_to_execution_change_duplicate_first_seen_setup_83850e08
					payload1 := buildLiveValidBlsToExecutionChange(ictx)
					ictx.StorePayload("seq_bls_to_execution_change_duplicate_first_seen", payload1)
					gtopic1 := irFullGossipTopic(ictx, "bls_to_execution_change")
					if ictx.GossipTopicOverride != "" {
						gtopic1 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic1 = ictx.CurrentTopic
					}
					gv1, gerr1 := cl.ObserveGossip(ctx, gtopic1, payload1, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv1, gerr1)))
					// step 2: cm_sequence_bls_to_execution_change_duplicate_first_seen_probe_83850e08
					payload2, _ := ictx.LoadPayload("seq_bls_to_execution_change_duplicate_first_seen")
					gtopic2 := irFullGossipTopic(ictx, "bls_to_execution_change")
					if ictx.GossipTopicOverride != "" {
						gtopic2 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic2 = ictx.CurrentTopic
					}
					gv2, gerr2 := cl.ObserveGossip(ctx, gtopic2, payload2, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv2, gerr2)))
					results[cl.Name()] = strings.Join(verdicts, "/")
				}
				return divergeValues(id, "cryptomsg", te, runner.DivAcceptReject, runner.SeverityHigh, results)
			},
		})
	}
	{
		id := "ir_seq.cryptomsg.generated_sequence.data_column_sidecar.duplicate_first_seen.51d0f050"
		specs = append(specs, runner.Spec{
			ID: id, Category: "cryptomsg",
			What:     "cryptomsg.generated_sequence.data_column_sidecar.duplicate_first_seen.51d0f050: 2-step sequence (1:cm_sequence_data_column_sidecar_duplicate_first_seen_setup_51d0f050 -> 2:cm_sequence_data_column_sidecar_duplicate_first_seen_probe_51d0f050)",
			Metadata: runner.Metadata{SpecRules: []string{"DATA_COLUMN_SIDECAR-IGNORE-869c65a5"}, MinClients: 2},
			Run: func(ctx context.Context, te runner.TestEnv) []runner.Divergence {
				ictx := irNewContext(te)
				results := map[string]string{}
				for _, cl := range te.Clients {
					var verdicts []string
					// step 1: cm_sequence_data_column_sidecar_duplicate_first_seen_setup_51d0f050
					payload1 := buildLiveValidDataColumnSidecar(ictx)
					ictx.StorePayload("seq_data_column_sidecar_duplicate_first_seen", payload1)
					gtopic1 := irFullGossipTopic(ictx, "data_column_sidecar_0")
					if ictx.GossipTopicOverride != "" {
						gtopic1 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic1 = ictx.CurrentTopic
					}
					gv1, gerr1 := cl.ObserveGossip(ctx, gtopic1, payload1, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv1, gerr1)))
					// step 2: cm_sequence_data_column_sidecar_duplicate_first_seen_probe_51d0f050
					payload2, _ := ictx.LoadPayload("seq_data_column_sidecar_duplicate_first_seen")
					gtopic2 := irFullGossipTopic(ictx, "data_column_sidecar_0")
					if ictx.GossipTopicOverride != "" {
						gtopic2 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic2 = ictx.CurrentTopic
					}
					gv2, gerr2 := cl.ObserveGossip(ctx, gtopic2, payload2, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv2, gerr2)))
					results[cl.Name()] = strings.Join(verdicts, "/")
				}
				return divergeValues(id, "cryptomsg", te, runner.DivAcceptReject, runner.SeverityHigh, results)
			},
		})
	}
	{
		id := "ir_seq.cryptomsg.generated_sequence.sync_committee_message.duplicate_first_seen.95e865c7"
		specs = append(specs, runner.Spec{
			ID: id, Category: "cryptomsg",
			What:     "cryptomsg.generated_sequence.sync_committee_message.duplicate_first_seen.95e865c7: 2-step sequence (1:cm_sequence_sync_committee_message_duplicate_first_seen_setup_95e865c7 -> 2:cm_sequence_sync_committee_message_duplicate_first_seen_probe_95e865c7)",
			Metadata: runner.Metadata{SpecRules: []string{"SYNC_COMMITTEE_MESSAGE-IGNORE-7708bbcf"}, MinClients: 2},
			Run: func(ctx context.Context, te runner.TestEnv) []runner.Divergence {
				ictx := irNewContext(te)
				results := map[string]string{}
				for _, cl := range te.Clients {
					var verdicts []string
					// step 1: cm_sequence_sync_committee_message_duplicate_first_seen_setup_95e865c7
					payload1 := buildLiveValidSyncCommitteeMessage(ictx)
					ictx.StorePayload("seq_sync_committee_message_duplicate_first_seen", payload1)
					gtopic1 := irFullGossipTopic(ictx, "sync_committee_0")
					if ictx.GossipTopicOverride != "" {
						gtopic1 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic1 = ictx.CurrentTopic
					}
					gv1, gerr1 := cl.ObserveGossip(ctx, gtopic1, payload1, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv1, gerr1)))
					// step 2: cm_sequence_sync_committee_message_duplicate_first_seen_probe_95e865c7
					payload2, _ := ictx.LoadPayload("seq_sync_committee_message_duplicate_first_seen")
					gtopic2 := irFullGossipTopic(ictx, "sync_committee_0")
					if ictx.GossipTopicOverride != "" {
						gtopic2 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic2 = ictx.CurrentTopic
					}
					gv2, gerr2 := cl.ObserveGossip(ctx, gtopic2, payload2, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv2, gerr2)))
					results[cl.Name()] = strings.Join(verdicts, "/")
				}
				return divergeValues(id, "cryptomsg", te, runner.DivAcceptReject, runner.SeverityHigh, results)
			},
		})
	}
	{
		id := "ir_seq.cryptomsg.generated_sequence.voluntary_exit.duplicate_first_seen.67af2c41"
		specs = append(specs, runner.Spec{
			ID: id, Category: "cryptomsg",
			What:     "cryptomsg.generated_sequence.voluntary_exit.duplicate_first_seen.67af2c41: 2-step sequence (1:cm_sequence_voluntary_exit_duplicate_first_seen_setup_67af2c41 -> 2:cm_sequence_voluntary_exit_duplicate_first_seen_probe_67af2c41)",
			Metadata: runner.Metadata{SpecRules: []string{"VOLUNTARY_EXIT-IGNORE-c9db1ebe"}, MinClients: 2},
			Run: func(ctx context.Context, te runner.TestEnv) []runner.Divergence {
				ictx := irNewContext(te)
				results := map[string]string{}
				for _, cl := range te.Clients {
					var verdicts []string
					// step 1: cm_sequence_voluntary_exit_duplicate_first_seen_setup_67af2c41
					payload1 := buildLiveValidVoluntaryExit(ictx)
					ictx.StorePayload("seq_voluntary_exit_duplicate_first_seen", payload1)
					gtopic1 := irFullGossipTopic(ictx, "voluntary_exit")
					if ictx.GossipTopicOverride != "" {
						gtopic1 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic1 = ictx.CurrentTopic
					}
					gv1, gerr1 := cl.ObserveGossip(ctx, gtopic1, payload1, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv1, gerr1)))
					// step 2: cm_sequence_voluntary_exit_duplicate_first_seen_probe_67af2c41
					payload2, _ := ictx.LoadPayload("seq_voluntary_exit_duplicate_first_seen")
					gtopic2 := irFullGossipTopic(ictx, "voluntary_exit")
					if ictx.GossipTopicOverride != "" {
						gtopic2 = ictx.GossipTopicOverride
					}
					if ictx.CurrentTopic != "" {
						gtopic2 = ictx.CurrentTopic
					}
					gv2, gerr2 := cl.ObserveGossip(ctx, gtopic2, payload2, gossipWait)
					verdicts = append(verdicts, classOf(gossipOutcome(gv2, gerr2)))
					results[cl.Name()] = strings.Join(verdicts, "/")
				}
				return divergeValues(id, "cryptomsg", te, runner.DivAcceptReject, runner.SeverityHigh, results)
			},
		})
	}
	return specs
}
